### ISSUE TITLE
Future exception was never retrieved

### ISSUE THREAD

**Issue by sadhasivam** [EverythingMe/redshift_console#23]
I am getting following error in console quite often. not sure its a bug or something.
further my loads tab never populated ?

```
[E 151009 16:01:50 concurrent:122] Future exception was never retrieved: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python2.7/site-packages/redshift_console/redshift.py", line 76, in start
        yield self._refresh()
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python2.7/site-packages/redshift_console/redshift.py", line 105, in _refresh
        yield self.refresh()
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python2.7/site-packages/redshift_console/redshift.py", line 276, in refresh
        yield self._fetch_load_errors()
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/site-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/site-packages/tornado/gen.py", line 812, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.7/site-packages/redshift_console/redshift.py", line 310, in _fetch_load_errors
        row['table'] = self.table_id_mapping[row['table_id']]['table_name']
    KeyError: 169366
[I 151009 16:01:52 web:1825] 304 GET /api/queries/inflight (::1) 0.48ms
```

**Comment by arikfr** [comment]
Indeed looks like a bug.

The user you're running redshift-console with, does it have sufficient privileges to read the schema?

**Comment by sadhasivam** [comment]
Yes. i am connecting with a `user` having `root` user previlages. if you have any specific user previlage requirement i can happy to assert that as well.

**Comment by arikfr** [comment]
Re. Loads tab not populating - currently it supposed to show only load errors. Do you know if you had any load errors when you checked it?

**Comment by sadhasivam** [comment]
yes we do have errors reported in `STL_LOAD_ERRORS` table.  but those errors not showing up in the load table tab.
